twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    # TWIG global variables accessible from all templates
    globals:
        application: '%application%'